In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# Any results you write to the current directory are saved as output.

/kaggle/input/ipl-2019-project-cricket/dataset.csv


In [2]:
df = pd.read_csv('/kaggle/input/ipl-2019-project-cricket/dataset.csv')
df = df[df['category']=='Bowler']
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 57 entries, 4 to 118
Data columns (total 100 columns):
player_name                 57 non-null object
category                    57 non-null object
age                         57 non-null int64
base_price                  57 non-null object
sold                        57 non-null int64
domestic                    57 non-null int64
average_all                 57 non-null int64
50s_all                     57 non-null int64
100s_all                    57 non-null int64
balls_all                   57 non-null int64
mdns_all                    57 non-null int64
runs-given_all              57 non-null int64
wkts-taken_all              57 non-null int64
average-bowl_all            57 non-null int64
CT_all                      57 non-null int64
matches_odi                 57 non-null int64
innings_odi                 57 non-null int64
not-out_odi                 57 non-null int64
runs_odi                    57 non-null int64
high-score_odi    

In [3]:
df['sold'].value_counts()

0    42
1    15
Name: sold, dtype: int64

In [4]:
df = df[['age','sold','domestic','runs-given_all','wkts-taken_all','balls_all','average-bowl_all','balls_first-class','average-bowl_first-class','runs-given_first-class','wkts-taken_first-class','matches_first-class','balls_listA','average-bowl_listA','runs-given_listA','wkts-taken_listA','matches_listA','matches_t20','balls_t20','average-bowl_t20','runs-given_t20','wkts-taken_t20']]

In [5]:
import numpy as np
df['runs-given_all'] = df['runs-given_all'].astype('float64')
df['runs-given_first-class'] = df['runs-given_first-class'].astype('float64')
df['runs-given_listA'] = df['runs-given_listA'].astype('float64')
df['runs-given_t20'] = df['runs-given_t20'].astype('float64')

In [6]:
def economy_rate(runs_given_list,balls_l):
    
    def calc_econ(runs_given,balls):
        runs_given = np.float64(runs_given)
        if balls == 0:
            return 0
        else:
            return((runs_given*6)/balls)
    
    econ_array = []
    for i in range(len(runs_given_list)):
        temp = calc_econ(runs_given_list[i],balls_l[i])
        econ_array.append(temp)
    
    return econ_array

In [7]:
economy_rate_overall = economy_rate(df['runs-given_all'].values,df['balls_all'].values)
df['economy_rate_overall'] = economy_rate_overall

In [8]:
economy_rate_listA = economy_rate(df['runs-given_listA'].values,df['balls_listA'].values)
df['economy_rate_listA'] = economy_rate_listA

In [9]:
economy_rate_first_class = economy_rate(df['runs-given_first-class'].values,df['balls_first-class'].values)
df['economy_rate_first-class'] = economy_rate_first_class

economy_rate_t20 = economy_rate(df['runs-given_t20'].values,df['balls_t20'].values)
df['economy_rate_t20'] = economy_rate_t20

In [10]:
df = df.drop(columns = ['runs-given_all','balls_all','runs-given_first-class','balls_first-class','runs-given_listA','balls_listA','runs-given_t20','balls_t20'])

df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 57 entries, 4 to 118
Data columns (total 18 columns):
age                         57 non-null int64
sold                        57 non-null int64
domestic                    57 non-null int64
wkts-taken_all              57 non-null int64
average-bowl_all            57 non-null int64
average-bowl_first-class    57 non-null int64
wkts-taken_first-class      57 non-null int64
matches_first-class         57 non-null int64
average-bowl_listA          57 non-null int64
wkts-taken_listA            57 non-null int64
matches_listA               57 non-null int64
matches_t20                 57 non-null int64
average-bowl_t20            57 non-null int64
wkts-taken_t20              57 non-null int64
economy_rate_overall        57 non-null float64
economy_rate_listA          57 non-null float64
economy_rate_first-class    57 non-null float64
economy_rate_t20            57 non-null float64
dtypes: float64(4), int64(14)
memory usage: 8.5 KB


In [11]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

clf_LR = LogisticRegression(random_state = 28, max_iter = 288)
clf_DT = DecisionTreeClassifier(criterion = 'entropy', max_depth = 5)

In [12]:
df_X = df.drop(columns = ['sold'])
df_y = df['sold']

X = df_X.values
y = df_y.values

clf_LR.fit(X,y)
clf_DT.fit(X,y)

y_true = y

y_pred_LR = clf_LR.predict(X)
y_pred_DT = clf_DT.predict(X)

/opt/conda/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [13]:
df_X.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 57 entries, 4 to 118
Data columns (total 17 columns):
age                         57 non-null int64
domestic                    57 non-null int64
wkts-taken_all              57 non-null int64
average-bowl_all            57 non-null int64
average-bowl_first-class    57 non-null int64
wkts-taken_first-class      57 non-null int64
matches_first-class         57 non-null int64
average-bowl_listA          57 non-null int64
wkts-taken_listA            57 non-null int64
matches_listA               57 non-null int64
matches_t20                 57 non-null int64
average-bowl_t20            57 non-null int64
wkts-taken_t20              57 non-null int64
economy_rate_overall        57 non-null float64
economy_rate_listA          57 non-null float64
economy_rate_first-class    57 non-null float64
economy_rate_t20            57 non-null float64
dtypes: float64(4), int64(13)
memory usage: 8.0 KB


In [14]:
from sklearn.metrics import confusion_matrix
print("confusion matrix for Logistic regression")
print (confusion_matrix(y_true,y_pred_LR))

print('confusion matrix for decision trees')
print(confusion_matrix(y_true,y_pred_DT))

confusion matrix for Logistic regression
[[39  3]
 [ 8  7]]
confusion matrix for decision trees
[[42  0]
 [ 0 15]]


In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)
import collections
collections.Counter(y_test)

Counter({1: 5, 0: 7})

Test case has 5 sold cases and 7 unsold cases. Total sold cases in the data-set is 15.

In [17]:
clf_DT_1 = DecisionTreeClassifier(criterion = 'entropy', max_depth = 5)
clf_DT_1.fit(X_train,y_train)

y_true = y_test
y_pred = clf_DT_1.predict(X_test)

print('confusion matrix for decision trees (with train and test split)')
print(confusion_matrix(y_true,y_pred))

confusion matrix for decision trees (with train and test split)
[[4 3]
 [2 3]]


In [18]:
clf_LR_1 = LogisticRegression(random_state = 28, max_iter = 288)
clf_LR_1.fit(X_train,y_train)

y_true = y_test
y_pred = clf_LR_1.predict(X_test)

print('confusion matrix for lOGISTIC REGRESSION (with train and test split)')
print(confusion_matrix(y_true,y_pred))

confusion matrix for lOGISTIC REGRESSION (with train and test split)
[[7 0]
 [5 0]]


/opt/conda/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


----END-----