In [1]:
import pandas as pd

In [2]:
file_path = "D:/UMD/Project/data-sets/Data-set-1.0.csv"
df = pd.read_csv(file_path)

In [3]:
df.columns

Index(['player_name', 'category', 'Age', 'base_price', 'sold ', 'domestic',
       'Matches', 'Innings', 'Not-out', 'Runs', 'HS', 'Average', '50s', '100s',
       'Balls', 'Mdns', 'RG', 'WT', 'AVGB', 'CT', 'ST'],
      dtype='object')

In [4]:
df = df.rename(columns = {'sold ':'sold'})
df.columns

Index(['player_name', 'category', 'Age', 'base_price', 'sold', 'domestic',
       'Matches', 'Innings', 'Not-out', 'Runs', 'HS', 'Average', '50s', '100s',
       'Balls', 'Mdns', 'RG', 'WT', 'AVGB', 'CT', 'ST'],
      dtype='object')

In [5]:
df.fillna(0)
df['Average'].fillna(0)
df['AVGB'].fillna(0)

def category_encoder(y):
    if str(y) == "Batsman":
        y = 1
    elif str(y) == "Bowler":
        y = 2
    elif str(y) == "Wicket Keeper":
        y = 3
    else:
        y = 4
    return y

df["category"] = df["category"].apply(lambda x : category_encoder(x))

In [6]:
df['Average']

0      3872
1      4190
2      5880
3      3488
4      1358
5      3709
6      2872
7         0
8      1366
9      2468
10     3822
11     2318
12     3170
13     1570
14     1858
15     1839
16     1390
17     1934
18      856
19     4373
20      768
21     2483
22     1954
23      692
24     1370
25     1070
26     9228
27     2587
28     2087
29      625
       ... 
154    4389
155    1806
156    2144
157    2278
158    2440
159    2791
160    4676
161    2085
162    3771
163    4380
164    1170
165    2895
166    5546
167    1908
168    2753
169    3026
170    1875
171    3300
172    1369
173    1625
174    2213
175    3406
176    2971
177     650
178     640
179    5672
180    5038
181    1782
182    3312
183    3683
Name: Average, Length: 184, dtype: int64

In [7]:
import re
df["base_price"] = df["base_price"].apply(lambda x : x.replace(",",""))
df["base_price"] = df["base_price"].apply(lambda x : x.replace("?",""))

import numpy as np
df = df.astype({'base_price':np.int64})

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 184 entries, 0 to 183
Data columns (total 21 columns):
player_name    184 non-null object
category       184 non-null int64
Age            184 non-null int64
base_price     184 non-null int64
sold           184 non-null int64
domestic       184 non-null int64
Matches        184 non-null int64
Innings        184 non-null int64
Not-out        184 non-null int64
Runs           184 non-null int64
HS             184 non-null int64
Average        184 non-null int64
50s            184 non-null int64
100s           184 non-null int64
Balls          184 non-null int64
Mdns           184 non-null int64
RG             184 non-null int64
WT             184 non-null int64
AVGB           184 non-null int64
CT             184 non-null int64
ST             184 non-null int64
dtypes: int64(20), object(1)
memory usage: 30.3+ KB


In [9]:
df.isna()

player_name  category    Age  base_price   sold  domestic  Matches  \
0          False     False  False       False  False     False    False   
1          False     False  False       False  False     False    False   
2          False     False  False       False  False     False    False   
3          False     False  False       False  False     False    False   
4          False     False  False       False  False     False    False   
5          False     False  False       False  False     False    False   
6          False     False  False       False  False     False    False   
7          False     False  False       False  False     False    False   
8          False     False  False       False  False     False    False   
9          False     False  False       False  False     False    False   
10         False     False  False       False  False     False    False   
11         False     False  False       False  False     False    False   
12         False     False  False       False  False     False    False   
13         False     False  False       False  False     False    False   
14         False     False  False       False  False     False    False   
15         False     False  False       False  False     False    False   
16         False     False  False       False  False     False    False   
17         False     False  False       False  False     False    False   
18         False     False  False       False  False     False    False   
19         False     False  False       False  False     False    False   
20         False     False  False       False  False     False    False   
21         False     False  False       False  False     False    False   
22         False     False  False       False  False     False    False   
23         False     False  False       False  False     False    False   
24         False     False  False       False  False     False    False   
25         False     False  False       False  False     False    False   
26         False     False  False       False  False     False    False   
27         False     False  False       False  False     False    False   
28         False     False  False       False  False     False    False   
29         False     False  False       False  False     False    False   
..           ...       ...    ...         ...    ...       ...      ...   
154        False     False  False       False  False     False    False   
155        False     False  False       False  False     False    False   
156        False     False  False       False  False     False    False   
157        False     False  False       False  False     False    False   
158        False     False  False       False  False     False    False   
159        False     False  False       False  False     False    False   
160        False     False  False       False  False     False    False   
161        False     False  False       False  False     False    False   
162        False     False  False       False  False     False    False   
163        False     False  False       False  False     False    False   
164        False     False  False       False  False     False    False   
165        False     False  False       False  False     False    False   
166        False     False  False       False  False     False    False   
167        False     False  False       False  False     False    False   
168        False     False  False       False  False     False    False   
169        False     False  False       False  False     False    False   
170        False     False  False       False  False     False    False   
171        False     False  False       False  False     False    False   
172        False     False  False       False  False     False    False   
173        False     False  False       False  False     False    False   
174        False     False  False       False  False     False    False   
175        False     False  Fa

In [10]:
X = df.drop(columns = ["player_name", "sold"]).values
y = df["sold"].values

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)


In [11]:
print('number of sold cases in y_train', np.count_nonzero(y_train))
print('number of sold cases in y_test', np.count_nonzero(y_test))

number of sold cases in y_train 36
number of sold cases in y_test 11


#### Logistic Regression Classifier

In [12]:
from sklearn.linear_model import LogisticRegression

LR_clf = LogisticRegression(random_state=0, solver='liblinear')
LR_clf.fit(X_train, y_train)

y_true = y_test
y_predict = LR_clf.predict(X_test)

In [13]:
from sklearn.metrics import confusion_matrix, accuracy_score

print("Confusion Matrix")
confusion_matrix(y_true, y_predict)

Confusion Matrix


array([[25,  1],
       [10,  1]], dtype=int64)

In [14]:
print("Accuracy Score")
accuracy_score(y_true, y_predict)

Accuracy Score


0.7027027027027027

In [15]:
print("y_true y_predict")
for i in range(len(y_true)):
    print(y_true[i], y_predict[i])

y_true y_predict
1 0
1 0
0 0
0 0
0 0
1 0
1 0
0 0
0 0
0 0
0 0
0 0
0 0
0 0
1 0
1 0
0 0
1 0
0 0
0 0
0 0
0 0
0 0
1 0
1 1
0 0
0 0
1 0
0 0
0 0
0 0
0 0
0 1
0 0
0 0
1 0
0 0


#### Decision Tree Classifier

In [16]:
from sklearn.tree import DecisionTreeClassifier

clf_DT = DecisionTreeClassifier(random_state = 28, max_depth = 5)
clf_DT.fit(X_train, y_train)

y_predict = clf_DT.predict(X_test)

print("y_true y_predict")
for i in range(len(y_true)):
    print(y_true[i], y_predict[i])

y_true y_predict
1 0
1 0
0 0
0 0
0 0
1 0
1 0
0 0
0 0
0 0
0 1
0 0
0 0
0 0
1 0
1 0
0 0
1 0
0 0
0 1
0 0
0 0
0 0
1 0
1 0
0 0
0 0
1 0
0 0
0 0
0 0
0 0
0 0
0 0
0 0
1 0
0 0


In [17]:
print("Confusion Matrix")
confusion_matrix(y_true, y_predict)

Confusion Matrix


array([[24,  2],
       [11,  0]], dtype=int64)

In [18]:
print("Accuracy Score")
accuracy_score(y_true, y_predict)

Accuracy Score


0.6486486486486487

#### Random Forest Classifier

In [19]:
from sklearn.ensemble import RandomForestClassifier

clf_RFC = RandomForestClassifier(random_state = 28, max_depth = 5, n_estimators = 40)
clf_RFC.fit(X_train, y_train)

y_predict = clf_RFC.predict(X_test)

print("y_true y_predict")
for i in range(len(y_true)):
    print(y_true[i], y_predict[i])

y_true y_predict
1 0
1 0
0 0
0 0
0 0
1 0
1 0
0 0
0 0
0 0
0 0
0 0
0 0
0 0
1 0
1 0
0 0
1 0
0 0
0 0
0 0
0 0
0 0
1 0
1 1
0 0
0 0
1 0
0 0
0 0
0 0
0 0
0 0
0 0
0 0
1 0
0 0


In [20]:
print("Confusion Matrix")
confusion_matrix(y_true, y_predict)

Confusion Matrix


array([[26,  0],
       [10,  1]], dtype=int64)

In [21]:
print("Accuracy Score")
accuracy_score(y_true, y_predict)

Accuracy Score


0.7297297297297297